#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "it-252.it.et.byu.edu";
$SERVER_PORT = 30021;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
